export const queixas = [
    "Dor no joelho",
    "Dor nas costas",
    "Dor no ombro",
    "Dor no tornozelo",
    "Dor no quadril",
    "Dor no pé",
    "Dor no punho",
    "Dor no cotovelo",
    "Dor no pescoço",
    "Dor muscular",
    "Entorses",
    "Fraturas",
    "Lesões ligamentares",
    "Lesões tendinosas",
    "Dificuldade de movimentação",
    "Inchaço nas articulações",
    "Formigamento nas extremidades",
    "Dificuldade para realizar atividades diárias",
    "Dor crônica",
    "Desalinhamento das articulações"
]
