// import tratamentosCardiacosCancelados from "./Cancelados/Cardiologia/tratamentos";
// import tratamentosCardiacosEmAndamento from "./EmAndamento/Cardiologia/tratamentos";
// import tratamentosCardiacosFinalizados from "./Finalizados/Cardiologia/tratamentos";
// import tratamentosFisioterapeuticosCancelados from "./Cancelados/Fisioterapia/tratamentos";
// import tratamentosFisioterapeuticosEmAndamento from "./EmAndamento/Fisioterapia/tratamentos";
// import tratamentosFisioterapeuticosFinalizados from "./Finalizados/Fisioterapia/tratamentos";
// import tratamentosGastroenterologicoCancelados from "./Cancelados/Gastroenterologista/tratamentos";
// import tratamentosGastroenterologicosEmAndamento from "./EmAndamento/Gastroenterologista/tratamentos";
// import tratamentosGastroenterologistaFinalizados from "./Finalizados/Gastroenterologista/tratamentos";
// import tratamentosOdontologicosCancelados from "./Cancelados/Odontologia/tratamentos";
// import tratamentosOdontologicosEmAndamento from "./EmAndamento/Odontologia/tratamentos";
// import tratamentosOdontologicosFinalizados from "./Finalizados/Odontologia/tratamentos";
// import tratamentosOftalmologicosCancelados from "./Cancelados/Oftalmologia/tratamentos";
// import tratamentosOftalmologicosEmAndamento from "./EmAndamento/Oftalmologia/tratamentos";
// import tratamentosOftamologicosFinalizados from "./Finalizados/Oftalmologia/tratamentos";
// import tratamentosOncologicosCancelados from "./Cancelados/Oncologia/tratamentos";
// import tratamentosOncologicosEmAndamento from "./EmAndamento/Oncologia/tratamentos";
// import tratamentosOncologicosFinalizados from "./Finalizados/Oncologia/tratamentos";
// import tratamentosOrtopedicosCancelados from "./Cancelados/Ortopedia/tratamentos";
// import tratamentosOrtopedicosEmAndamento from "./EmAndamento/Ortopedia/tratamentos";
// import tratamentosOrtopedicosFinalizados from "./Finalizados/Ortopedia/tratamentos";
// import tratamentosPediatricosCancelados from "./Cancelados/Pediatria/tratamentos";
// import tratamentosPediatricosEmAndamento from "./EmAndamento/Pediatria/tratamentos";
// import tratamentosPediatricosFinalizados from "./Finalizados/Pediatria/tratamentos";
// import tratamentosUTICancelado from "./Cancelados/UTI/tratamentos";
// import tratamentosUTIEmAndamento from "./EmAndamento/UTI/tratamentos";
// import tratamentosUTIFinalizados from "./Finalizados/UTI/tratamentos";

// export const tratamentosCardiacos = tratamentosCardiacosCancelados.concat(tratamentosCardiacosEmAndamento, tratamentosCardiacosFinalizados);
// export const tratamentosFisioterapeuticos = tratamentosFisioterapeuticosCancelados.concat(tratamentosFisioterapeuticosEmAndamento, tratamentosFisioterapeuticosFinalizados);
// export const tratamentosGastroenterologico = tratamentosGastroenterologicoCancelados.concat(tratamentosGastroenterologicosEmAndamento, tratamentosGastroenterologistaFinalizados);